In [5]:
# imports
import pandas as pd
import numpy as np

In [11]:
# importing csv's
claims = pd.read_csv('claims.csv')
members = pd.read_csv('members.csv')

In [37]:
# Billed total calculation
total_billed = claims['billed_amount'].sum().round(2)

# Paid total calculation
total_paid = claims['paid_amount'].sum().round(2)

# Difference between billed and paid amounts
total_difference = total_billed - total_paid

# Total number of claims
num_claims = claims['claim_id'].count()

# Average Unpaid Claim Cost calculation
avg_unpaid = (total_difference / num_claims).round(2)

In [39]:
# Sorting claims by paid_amount
claims.sort_values('paid_amount', ascending=False)

,claim_id,member_id,provider_id,claim_date,claim_type,cpt_code,icd_code,billed_amount,paid_amount
142,153,32,PRV00001,11/2/2023,Inpatient,45678,I10,42000.0,35000.0
21,22,6,PRV12345,11/3/2022,Inpatient,00123,A01.1,42000.0,31500.0
1,2,1,PRV00002,7/22/2023,Inpatient,67890,B99.4,32000.0,28000.0
356,372,82,PRV12345,2/15/2023,Inpatient,36512,A41.9,32000.0,25600.0
116,127,28,PRV00001,1/15/2023,Inpatient,12345,A12.3,32000.0,25600.0
...,...,...,...,...,...,...,...,...,...
175,188,40,PRV00002,5/22/2023,Pharmacy,31235,B20.9,75.0,60.0
156,169,35,PRV33333,4/4/2024,Pharmacy,GPI1234,J45.909,75.0,60.0
206,219,47,PRV10004,11/30/2023,Pharmacy,45678,D50.6,75.0,50.0
212,225,48,PRV00214,8/9/2023,Pharmacy,54321,Z00.00,210.0,0.0
5,6,2,PRV00456,6/20/2023,Inpatient,67890,B99.4,15250.0,0.0

In [81]:
top_cpt_code = claims[['cpt_code', 'paid_amount']].copy().groupby('cpt_code').sum().sort_values('paid_amount', ascending=False).head(10)

In [82]:
top_cpt_code['num_claims'] = claims.groupby(

          paid_amount
cpt_code
67890       242735.00
23456       203790.75
00123       122010.00
12345       115236.90
99223        57350.00
34567        54445.00
45678        52054.20
00567        38969.00
54321        36600.00
56789        33207.00

In [74]:
top_icd_code = claims[['icd_code', 'paid_amount']].copy()
top_icd_code.groupby('icd_code').sum().sort_values('paid_amount', ascending=False).head(10)

          paid_amount
icd_code
I10         259566.00
A12.3       152147.00
B20         140990.00
B20.1       105210.00
C34.91       62905.00
B99.4        51000.00
E11.65       50512.00
J45.909      44465.56
E11.9        34766.00
A01.1        34260.00

In [78]:
top_cpt_code['num_claims'] = top_cpt_code.groupby('cpt_code').count()['paid_amount']

In [79]:
top_cpt_code

    cpt_code  paid_amount  num_claims
0      12345       1600.0         NaN
1      67890      28000.0         NaN
2      23456        400.0         NaN
3      34567        120.0         NaN
4      12345       1680.0         NaN
..       ...          ...         ...
444    12345       1500.0         NaN
445    54321      14000.0         NaN
446    67890        320.0         NaN
447    11111        100.0         NaN
448    22222       3550.0         NaN

[449 rows x 3 columns]

In [69]:
top_cpt_code

    cpt_code  paid_amount  num_claims
0      12345       1600.0         NaN
1      67890      28000.0         NaN
2      23456        400.0         NaN
3      34567        120.0         NaN
4      12345       1680.0         NaN
..       ...          ...         ...
444    12345       1500.0         NaN
445    54321      14000.0         NaN
446    67890        320.0         NaN
447    11111        100.0         NaN
448    22222       3550.0         NaN

[449 rows x 3 columns]